spring:
  datasource:
    url: jdbc:mysql://localhost:3306/escuela?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Sistemas.1
    hikari:
           maximum-pool-size: 5
           connectionTimeout: 30000
           idleTimeout: 600000
           maxLifetime: 0
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: servicio-ilusion
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8091